# Use custom format
format = """
[┌───────────────────>](bold green)
[│](bold green)$all
[└─>](bold green) """

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

[kubernetes]
format = 'on [⛵ $context \($namespace\)](dimmed green)'
disabled = false
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"
